POST http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "My Second Blogpost", 
	"author": "Sarukei", 
	"url": "https://github.com/Sarukei/full-stack-open-2021", 
	"likes": 0
}