DELETE http://localhost:3001/api/blogs/61096111dea7c0026f62b88c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxMDk1NTkzMWNlOWYwNTFmZjc0ZWQxMSIsImlhdCI6MTYyODAwNTI4OX0.CgZB8JGqouKv95tYl7lNu6yxIG2b3L_FzBNMxSUBGqI